### ISSUE TITLE
Where is the ALCNet model？

### ISSUE THREAD

**Issue by CarpeDiemly** [YimianDai/open-alcnet#3]
I am very interested in your thesis, and I am currently studying related content. But I am a newcomer, and I want to ask you, where is the relevant implementation code of ALCNet? In open-alcnet/model/contrast.py/ and open-alcnet/model/segmentation.py/ here I don’t see class ALCNet{...}

**Comment by YimianDai** [comment]
Sorry for replying late... I didn't notice here are some issues if not someone reminds me.

The model for ALCNet is `MPCMResNetFPN` in `model/contrast.py`.

At first, when I writing code, I didn't came up with a good name. However, once the model params is got, I cannot change the class name otherwise it won't load the params file. Therefore, I left this wired name.

**Comment by CarpeDiemly** [comment]
Thank you for your reply. I have solved this problem last year by carefully comparing the paper and the code.
